# Return Minichunk info
import re
def minichunk_dict():
	# Return dict with minichunk with info
	# m_dict = {"Chunk Name": [["Minichunk Name" 0,
	# 					               "RE" 1, Re_num 2, dig_multiplier 3, X more input to gain same molar output
	# 												 "Antibiotic" 4]]} 
	#
	m_ls = minichunk_ls()
	m_dict = {}
	pattern = "\A\w+"
	for i in m_ls:
		c = re.search(pattern, i[0])
		chunk = c.group(0)
		if chunk in m_dict:
			m_dict[chunk].append(i)
		else:
			m_dict[chunk] = [i]
	# out = open("out.txt", "w")
	# for chunk in m_dict:
	# 	out.write("%s : %s\n" % (chunk, str(m_dict[chunk])))
	# out.close()
	return m_dict

def minichunk_ls():
  
  m_ls = [["AA1.01", "BsmBI", 3, 2,  "Kan"],
          ["AA1.02", "BsaI", 2, 1,  "Kan"],
          ["AA1.03", "BsmBI", 3, 2,  "Kan"],
          ["AA1.04", "BsmBI", 3, 2,  "Kan"],
          ["AA2.01", "BsmBI", 3, 2,  "Amp"],
          ["AA2.02", "NmeAIII", 4, 3,  "Amp"],
          ["AA2.03", "BsmBI", 3, 2,  "Kan"],
          ["AA3.01", "AarI", 1, 3,  "Kan"],
          ["AA3.02", "NmeAIII", 4, 6,  "Amp"],
          ["AA3.03", "NmeAIII", 4, 3,  "Amp"],
          ["AA4.01", "BsmBI", 3, 2,  "Amp"],
          ["AA4.02", "BsmBI", 3, 2,  "Amp"],
          ["AA4.03", "BsmBI", 3, 2,  "Amp"],
          ["AA5.01", "NmeAIII", 4, 2,  "Kan"],
          ["AA5.02", "BsmBI", 3, 2,  "Amp"],
          ["AA5.03", "BsmBI", 3, 2,  "Amp"],
          ["AA6.01", "BsmBI", 3, 2,  "Amp"],
          ["AA6.02", "BsmBI", 3, 2,  "Amp"],
          ["AA6.03", "BsmBI", 3, 2,  "Amp"],
          ["AA6.04", "BsmBI", 3, 2,  "Kan"],
          ["BB1.01", "NmeAIII", 4, 3,  "Amp"],
          ["BB1.02", "NmeAIII", 4, 3,  "Amp"],
          ["BB1.03", "BsmBI", 3, 2,  "Amp"],
          ["BB2.01", "NmeAIII", 4, 2,  "Kan"],
          ["BB2.02", "BsmBI", 3, 2,  "Kan"],
          ["BB2.03", "BsmBI", 3, 2,  "Amp"],
          ["BB3.01", "BsmBI", 3, 2,  "Amp"],
          ["BB3.02", "NmeAIII", 4, 6,  "Amp"],
          ["BB3.03", "NmeAIII", 4, 3,  "Amp"],
          ["BB3.04", "BsmBI", 3, 2,  "Amp"],
          ["BB4.01", "BsmBI", 3, 2,  "Amp"],
          ["BB4.02", "NmeAIII", 4, 3,  "Kan"],
          ["BB4.03", "BsmBI", 3, 2,  "Kan"],
          ["BB4.04", "NmeAIII", 4, 3,  "Amp"],
          ["BB5.01", "BsmBI", 3, 2,  "Amp"],
          ["BB5.02", "NmeAIII", 4, 3,  "Amp"],
          ["BB5.03", "BsmBI", 3, 2,  "Amp"],
          ["BB5.04", "NmeAIII", 4, 3,  "Amp"],
          ["CC1.01", "BsmBI", 3, 2,  "Amp"],
          ["CC1.02", "BsmBI", 3, 2,  "Amp"],
          ["CC1.03", "BsmBI", 3, 2,  "Amp"],
          ["CC2.01", "NmeAIII", 4, 3,  "Amp"],
          ["CC2.02", "BsmBI", 3, 2,  "Kan"],
          ["CC2.03", "BsmBI", 3, 2,  "Kan"],
          ["CC3.01", "NmeAIII", 4, 3,  "Kan"],
          ["CC3.02", "BsmBI", 3, 2,  "Kan"],
          ["CC3.03", "BsmBI", 3, 2,  "Kan"],
          ["CC3.04", "BsmBI", 3, 2,  "Amp"],
          ["CC4.01", "NmeAIII", 4, 3,  "Amp"],
          ["CC4.02", "NmeAIII", 4, 3,  "Amp"],
          ["CC4.03", "NmeAIII", 4, 3,  "Kan"],
          ["CC5.01", "BsmBI", 3, 2,  "Kan"],
          ["CC5.02", "NmeAIII", 4, 3,  "Amp"],
          ["CC5.03", "BsmBI", 3, 2,  "Amp"],
          ["CC5.04", "BsmBI", 3, 2,  "Amp"],
          ["CC6.01", "NmeAIII", 4, 6,  "Amp"],
          ["CC6.02", "NmeAIII", 4, 2,  "Kan"],
          ["CC6.03", "NmeAIII", 4, 2,  "Kan"],
          ["CC6.04", "NmeAIII", 4, 2,  "Kan"],
          ["DD1.01", "NmeAIII", 4, 3,  "Amp"],
          ["DD1.02", "AarI", 1, 3,  "Kan"],
          ["DD1.03", "BsmBI", 3, 2,  "Amp"],
          ["DD2.01", "BsmBI", 3, 2,  "Amp"],
          ["DD2.02", "BsmBI", 3, 2,  "Amp"],
          ["DD2.03", "BsmBI", 3, 2,  "Amp"],
          ["DD2.04", "BsmBI", 3, 2,  "Amp"],
          ["DD3.01", "BsmBI", 3, 2,  "Kan"],
          ["DD3.02", "BsaI", 2, 2,  "Kan"],
          ["DD3.03", "AarI", 1, 3,  "Kan"],
          ["DD3.04", "BsmBI", 3, 2,  "Amp"],
          ["DD4.01", "BsmBI", 3, 2,  "Kan"],
          ["DD4.02", "BsmBI", 3, 2,  "Amp"],
          ["DD4.03", "BsmBI", 3, 2,  "Amp"],
          ["DD4.04", "BsmBI", 3, 2,  "Amp"],
          ["DD5.01", "BsmBI", 3, 2,  "Kan"],
          ["DD5.02", "BsmBI", 3, 2,  "Kan"],
          ["DD5.03", "NmeAIII", 4, 3,  "Amp"],
          ["DD5.04", "NmeAIII", 4, 3,  "Amp"],
          ["EE1.01", "BsmBI", 3, 2,  "Amp"],
          ["EE1.02", "BsmBI", 3, 2,  "Amp"],
          ["EE1.03", "BsaI", 2, 1,  "Kan"],
          ["EE1.04", "BsmBI", 3, 2,  "Amp"],
          ["EE2.01", "BsmBI", 3, 2,  "Kan"],
          ["EE2.02", "NmeAIII", 4, 3,  "Amp"],
          ["EE2.03", "BsmBI", 3, 2,  "Kan"],
          ["EE2.04", "BsmBI", 3, 2,  "Amp"],
          ["EE3.01", "NmeAIII", 4, 6,  "Amp"],
          ["EE3.02", "BsmBI", 3, 2,  "Amp"],
          ["EE3.03", "NmeAIII", 4, 2,  "Kan"],
          ["EE3.04", "AarI", 1, 3,  "Kan"],
          ["EE4.01", "NmeAIII", 4, 3,  "Amp"],
          ["EE4.02", "NmeAIII", 4, 2,  "Kan"],
          ["EE4.03", "NmeAIII", 4, 3,  "Kan"],
          ["EE4.04", "NmeAIII", 4, 3,  "Amp"],
          ["EE5.01", "NmeAIII", 4, 3,  "Amp"],
          ["EE5.02", "BsmBI", 3, 2,  "Kan"],
          ["EE5.03", "BsmBI", 3, 2,  "Kan"],
          ["EE5.04", "BsmBI", 3, 2,  "Kan"],
          ["FF1.01", "NmeAIII", 4, 6,  "Amp"],
          ["FF1.02", "BsmBI", 3, 2,  "Amp"],
          ["FF1.03", "BsmBI", 3, 2,  "Amp"],
          ["FF1.04", "BsmBI", 3, 2,  "Amp"],
          ["FF2.01", "BsmBI", 3, 2,  "Kan"],
          ["FF2.02", "BsmBI", 3, 2,  "Amp"],
          ["FF2.03", "BsmBI", 3, 2,  "Kan"],
          ["FF3.01", "BsmBI", 3, 2,  "Amp"],
          ["FF3.02", "NmeAIII", 4, 3,  "Amp"],
          ["FF3.03", "BsmBI", 3, 2,  "Amp"],
          ["FF3.04", "BsmBI", 3, 2,  "Amp"],
          ["FF4.01", "BsaI", 2, 2,  "Amp"],
          ["FF4.01", "BsaI", 2, 2,  "Kan"],
          ["FF4.02", "BsmBI", 3, 2,  "Kan"],
          ["FF4.03", "BsmBI", 3, 2,  "Kan"],
          ["FF4.04", "BsaI", 2, 2,  "Kan"],
          ["FF5.01", "BsmBI", 3, 2,  "Amp"],
          ["FF5.02", "BsmBI", 3, 2,  "Amp"],
          ["FF5.03", "BsmBI", 3, 2,  "Kan"],
          ["FF5.04", "NmeAIII", 4, 2,  "Kan"],
          ["GG1.01", "NmeAIII", 4, 3,  "Amp"],
          ["GG1.02", "NmeAIII", 4, 3,  "Amp"],
          ["GG1.03", "BsmBI", 3, 2,  "Amp"],
          ["GG2.01", "NmeAIII", 4, 2,  "Kan"],
          ["GG2.02", "BsmBI", 3, 2,  "Amp"],
          ["GG2.03", "NmeAIII", 4, 3,  "Amp"],
          ["GG3.01", "BsmBI", 3, 2,  "Amp"],
          ["GG3.02", "BsmBI", 3, 2,  "Kan"],
          ["GG3.03", "BsmBI", 3, 2,  "Amp"],
          ["GG3.04", "NmeAIII", 4, 3,  "Amp"],
          ["GG4.01", "NmeAIII", 4, 3,  "Amp"],
          ["GG4.02", "BsmBI", 3, 2,  "Amp"],
          ["GG4.03", "NmeAIII", 4, 3,  "Amp"],
          ["GG4.04", "NmeAIII", 4, 3,  "Amp"],
          ["GG5.01", "NmeAIII", 4, 6,  "Amp"],
          ["GG5.02", "BsmBI", 3, 2,  "Amp"],
          ["GG5.03", "BsmBI", 3, 2,  "Amp"],
          ["GG5.04", "BsmBI", 3, 2,  "Amp"],
          ["HH1.01", "BsmBI", 3, 2,  "Amp"],
          ["HH1.02", "BsmBI", 3, 1,  "Kan"],
          ["HH1.03", "BsmBI", 3, 2,  "Amp"],
          ["HH2.01", "BsmBI", 3, 2,  "Amp"],
          ["HH2.02", "BsmBI", 3, 2,  "Kan"],
          ["HH2.03", "AarI", 1, 3,  "Kan"],
          ["HH3.01", "BsmBI", 3, 2,  "Amp"],
          ["HH3.02", "NmeAIII", 4, 3,  "Amp"],
          ["HH3.03", "NmeAIII", 4, 2,  "Kan"],
          ["HH3.04", "BsmBI", 3, 2,  "Amp"],
          ["HH4.01", "NmeAIII", 4, 3,  "Amp"],
          ["HH4.02", "BsmBI", 3, 2,  "Amp"],
          ["HH4.03", "BsmBI", 3, 2,  "Amp"],
          ["HH5.01", "NmeAIII", 4, 3,  "Amp"],
          ["HH5.02", "NmeAIII", 4, 6,  "Amp"],
          ["HH5.03", "NmeAIII", 4, 2,  "Kan"],
          ["HH5.04", "AarI", 1, 3,  "Kan"],
          ["II1.01", "AarI", 1, 1,  "Kan"],
          ["II1.02", "NmeAIII", 4, 3,  "Amp"],
          ["II1.03", "NmeAIII", 4, 2,  "Kan"],
          ["II1.04", "BsmBI", 3, 2,  "Kan"],
          ["II2.01", "BsmBI", 3, 2,  "Kan"],
          ["II2.02", "NmeAIII", 4, 6,  "Amp"],
          ["II2.03", "NmeAIII", 4, 6,  "Amp"],
          ["II2.04", "BsmBI", 3, 2,  "Kan"],
          ["II3.01", "NmeAIII", 4, 3,  "Amp"],
          ["II3.02", "NmeAIII", 4, 2,  "Kan"],
          ["II3.03", "BsmBI", 3, 2,  "Amp"],
          ["II4.01", "BsmBI", 3, 1,  "Kan"],
          ["II4.02", "BsmBI", 3, 2,  "Kan"],
          ["II4.03", "NmeAIII", 4, 2,  "Kan"],
          ["II4.04", "NmeAIII", 4, 3,  "Amp"],
          ["II5.01", "BsmBI", 3, 2,  "Amp"],
          ["II5.02", "NmeAIII", 4, 3,  "Amp"],
          ["II5.03", "NmeAIII", 4, 2,  "Kan"],
          ["II5.04", "BsmBI", 3, 2,  "Kan"],
          ["JJ1.01", "BsmBI", 3, 2,  "Kan"],
          ["JJ1.02", "NmeAIII", 4, 6,  "Amp"],
          ["JJ1.03", "BsmBI", 3, 2,  "Amp"],
          ["JJ2.01", "BsmBI", 3, 2,  "Amp"],
          ["JJ2.02", "BsmBI", 3, 2,  "Kan"],
          ["JJ2.03", "NmeAIII", 4, 3,  "Amp"],
          ["JJ2.04", "BsmBI", 3, 2,  "Kan"],
          ["JJ3.01", "BsmBI", 3, 2,  "Amp"],
          ["JJ3.02", "AarI", 1, 3,  "Kan"],
          ["JJ3.03", "BsmBI", 3, 2,  "Amp"],
          ["JJ4.01", "BsmBI", 3, 2,  "Amp"],
          ["JJ4.02", "BsmBI", 3, 2,  "Kan"],
          ["JJ4.03", "BsmBI", 3, 2,  "Kan"],
          ["JJ4.04", "AarI", 1, 3,  "Kan"],
          ["JJ5.01", "BsmBI", 3, 2,  "Amp"],
          ["JJ5.02", "NmeAIII", 4, 2,  "Kan"],
          ["K1.01", "BsmBI", 3, 2,  "Amp"],
          ["K1.02", "NmeAIII", 4, 3,  "Amp"],
          ["K1.03", "BsmBI", 3, 2,  "Kan"],
          ["K2.01", "BsmBI", 3, 2,  "Amp"],
          ["K2.02", "BsmBI", 3, 2,  "Amp"],
          ["K2.03", "BsmBI", 3, 2,  "Amp"],
          ["K3.01", "BsmBI", 3, 2,  "Amp"],
          ["K3.02", "BsmBI", 3, 2,  "Kan"],
          ["K3.03", "BsmBI", 3, 2,  "Kan"],
          ["K4.01", "BsmBI", 3, 2,  "Amp"],
          ["K4.02", "BsmBI", 3, 2,  "Amp"],
          ["K4.03", "NmeAIII", 4, 2,  "Kan"],
          ["K4.04", "BsmBI", 3, 2,  "Amp"],
          ["K5.01", "BsmBI", 3, 2,  "Kan"],
          ["K5.02", "BsmBI", 3, 2,  "Amp"],
          ["K5.03", "NmeAIII", 4, 6,  "Amp"],
          ["K5.04", "BsmBI", 3, 2,  "Amp"],
          ["L1.01", "BsmBI", 3, 2,  "Amp"],
          ["L1.02", "BsmBI", 3, 2,  "Kan"],
          ["L1.03", "BsmBI", 3, 2,  "Amp"],
          ["L2.01", "BsmBI", 3, 2,  "Amp"],
          ["L2.02", "NmeAIII", 4, 6,  "Amp"],
          ["L2.03", "NmeAIII", 4, 6,  "Amp"],
          ["L3.01", "NmeAIII", 4, 3,  "Amp"],
          ["L3.02", "BsmBI", 3, 2,  "Amp"],
          ["L3.03", "NmeAIII", 4, 3,  "Amp"],
          ["L4.01", "NmeAIII", 4, 2,  "Kan"],
          ["L4.02", "NmeAIII", 4, 2,  "Kan"],
          ["L4.03", "NmeAIII", 4, 6,  "Amp"],
          ["L5.01", "BsmBI", 3, 2,  "Amp"],
          ["L5.02", "BsmBI", 3, 2,  "Amp"],
          ["L5.03", "NmeAIII", 4, 3,  "Amp"],
          ["L5.04", "AarI", 1, 3,  "Kan"],
          ["M1.01", "NmeAIII", 4, 3,  "Amp"],
          ["M1.02", "NmeAIII", 4, 2,  "Kan"],
          ["M1.03", "NmeAIII", 4, 2,  "Kan"],
          ["M2.01", "BsmBI", 3, 2,  "Amp"],
          ["M2.02", "NmeAIII", 4, 3,  "Amp"],
          ["M2.03", "NmeAIII", 4, 6,  "Amp"],
          ["M3.01", "BsmBI", 3, 2,  "Kan"],
          ["M3.02", "BsmBI", 3, 2,  "Amp"],
          ["M3.03", "BsmBI", 3, 2,  "Kan"],
          ["M3.04", "BsmBI", 3, 2,  "Kan"],
          ["M4.01", "BsmBI", 3, 2,  "Kan"],
          ["M4.02", "BsmBI", 3, 2,  "Amp"],
          ["M4.03", "BsmBI", 3, 2,  "Kan"],
          ["M4.04", "BsmBI", 3, 2,  "Kan"],
          ["M5.01", "NmeAIII", 4, 2,  "Kan"],
          ["M5.02", "BsmBI", 3, 2,  "Amp"],
          ["M5.03", "BsmBI", 3, 2,  "Amp"],
          ["M5.04", "BsmBI", 3, 2,  "Kan"],
          ["N1.01", "BsmBI", 3, 2,  "Amp"],
          ["N1.02", "BsmBI", 3, 2,  "Kan"],
          ["N1.03", "NmeAIII", 4, 3,  "Amp"],
          ["N1.04", "BsmBI", 3, 2,  "Amp"],
          ["N2.01", "AarI", 1, 3,  "Kan"],
          ["N2.02", "BsmBI", 3, 2,  "Kan"],
          ["N2.03", "BsmBI", 3, 2,  "Kan"],
          ["N3.01", "BsmBI", 3, 2,  "Amp"],
          ["N3.02", "BsmBI", 3, 2,  "Amp"],
          ["N3.03", "NmeAIII", 4, 6,  "Amp"],
          ["N4.01", "NmeAIII", 4, 3,  "Amp"],
          ["N4.02", "BsmBI", 3, 2,  "Kan"],
          ["N4.03", "BsmBI", 3, 2,  "Amp"],
          ["N4.04", "NmeAIII", 4, 3,  "Amp"],
          ["N5.01", "NmeAIII", 4, 3,  "Kan"],
          ["N5.02", "NmeAIII", 4, 3,  "Amp"],
          ["N5.03", "BsmBI", 3, 2,  "Kan"],
          ["N5.04", "NmeAIII", 4, 2,  "Kan"],
          ["O1.01", "NmeAIII", 4, 2,  "Kan"],
          ["O1.02", "NmeAIII", 4, 6,  "Amp"],
          ["O1.03", "NmeAIII", 4, 3,  "Amp"],
          ["O2.01", "NmeAIII", 4, 3,  "Amp"],
          ["O2.02", "NmeAIII", 4, 3,  "Amp"],
          ["O2.03", "BsmBI", 3, 2,  "Amp"],
          ["O3.01", "BsmBI", 3, 2,  "Amp"],
          ["O3.02", "BsmBI", 3, 2,  "Kan"],
          ["O3.03", "NmeAIII", 4, 3,  "Amp"],
          ["O3.04", "BsmBI", 3, 2,  "Amp"],
          ["O4.01", "BsmBI", 3, 2,  "Kan"],
          ["O4.02", "BsmBI", 3, 2,  "Amp"],
          ["O4.03", "BsmBI", 3, 2,  "Kan"],
          ["O5.01", "BsmBI", 3, 2,  "Amp"],
          ["O5.02", "BsmBI", 3, 2,  "Kan"],
          ["O5.03", "BsmBI", 3, 2,  "Amp"],
          ["O5.04", "NmeAIII", 4, 2,  "Kan"],
          ["O6.01", "BsmBI", 3, 2,  "Amp"],
          ["O6.02", "BsmBI", 3, 2,  "Amp"],
          ["O6.03", "NmeAIII", 4, 3,  "Kan"],
          ["O6.04", "BsmBI", 3, 2,  "Amp"],
          ["P1.01", "NmeAIII", 4, 2,  "Kan"],
          ["P1.02", "BsmBI", 3, 2,  "Amp"],
          ["P1.03", "BsmBI", 3, 2,  "Amp"],
          ["P2.01", "BsmBI", 3, 2,  "Amp"],
          ["P2.02", "NmeAIII", 4, 2,  "Kan"],
          ["P2.03", "BsmBI", 3, 2,  "Kan"],
          ["P3.01", "BsmBI", 3, 2,  "Kan"],
          ["P3.02", "NmeAIII", 4, 3,  "Amp"],
          ["P3.03", "BsmBI", 3, 2,  "Kan"],
          ["P4.01", "BsmBI", 3, 2,  "Amp"],
          ["P4.02", "BsmBI", 3, 2,  "Amp"],
          ["P4.03", "BsmBI", 3, 2,  "Kan"],
          ["P5.01", "BsmBI", 3, 2,  "Amp"],
          ["P5.02", "BsaI", 2, 1,  "Kan"],
          ["P5.03", "AarI", 1, 1,  "Kan"],
          ["P5.04", "NmeAIII", 4, 3,  "Amp"],
          ["Q1.01", "NmeAIII", 4, 3,  "Amp"],
          ["Q1.02", "BsmBI", 3, 2,  "Kan"],
          ["Q1.03", "NmeAIII", 4, 3,  "Amp"],
          ["Q1.04", "BsmBI", 3, 2,  "Kan"],
          ["Q2.01", "BsmBI", 3, 2,  "Kan"],
          ["Q2.02", "BsmBI", 3, 2,  "Kan"],
          ["Q2.03", "BsmBI", 3, 2,  "Amp"],
          ["Q3.01", "BsmBI", 3, 2,  "Amp"],
          ["Q3.02", "BsmBI", 3, 2,  "Amp"],
          ["Q3.03", "NmeAIII", 4, 6,  "Amp"],
          ["Q4.01", "BsmBI", 3, 2,  "Amp"],
          ["Q4.02", "NmeAIII", 4, 2,  "Kan"],
          ["Q4.03", "BsmBI", 3, 2,  "Kan"],
          ["Q4.04", "BsmBI", 3, 2,  "Kan"],
          ["Q5.01", "BsmBI", 3, 2,  "Kan"],
          ["Q5.02", "BsmBI", 3, 2,  "Kan"],
          ["Q5.03", "BsmBI", 3, 2,  "Kan"],
          ["Q5.04", "BsmBI", 3, 2,  "Amp"],
          ["R1.01", "BsmBI", 3, 2,  "Kan"],
          ["R1.02", "BsaI", 2, 2,  "Kan"],
          ["R1.03", "BsmBI", 3, 2,  "Kan"],
          ["R2.01", "BsmBI", 3, 2,  "Amp"],
          ["R2.02", "BsmBI", 3, 2,  "Amp"],
          ["R2.03", "BsmBI", 3, 2,  "Amp"],
          ["R3.01", "BsmBI", 3, 2,  "Amp"],
          ["R3.02", "NmeAIII", 4, 3,  "Amp"],
          ["R3.03", "NmeAIII", 4, 3,  "Kan"],
          ["R4.01", "BsmBI", 3, 2,  "Kan"],
          ["R4.02", "BsmBI", 3, 2,  "Amp"],
          ["R4.03", "NmeAIII", 4, 3,  "Amp"],
          ["R5.01", "BsmBI", 3, 2,  "Amp"],
          ["R5.02", "BsmBI", 3, 2,  "Kan"],
          ["R5.03", "BsmBI", 3, 2,  "Amp"],
          ["R5.04", "AarI", 1, 3,  "Kan"],
          ["S1.01", "NmeAIII", 4, 2,  "Kan"],
          ["S1.02", "NmeAIII", 4, 3,  "Amp"],
          ["S1.03", "BsaI", 2, 2,  "Kan"],
          ["S1.04", "BsmBI", 3, 2,  "Kan"],
          ["S2.01", "BsmBI", 3, 1,  "Kan"],
          ["S2.02", "BsmBI", 3, 2,  "Kan"],
          ["S2.03", "BsmBI", 3, 2,  "Amp"],
          ["S2.04", "AarI", 1, 3,  "Kan"],
          ["S3.01", "BsmBI", 3, 2,  "Amp"],
          ["S3.02", "BsmBI", 3, 2,  "Amp"],
          ["S3.03", "BsmBI", 3, 2,  "Amp"],
          ["S3.04", "BsmBI", 3, 2,  "Kan"],
          ["S4.01", "BsmBI", 3, 2,  "Kan"],
          ["S4.02", "NmeAIII", 4, 6,  "Amp"],
          ["S4.03", "BsmBI", 3, 2,  "Kan"],
          ["S5.01", "BsmBI", 3, 2,  "Amp"],
          ["S5.02", "NmeAIII", 4, 3,  "Amp"],
          ["S5.03", "NmeAIII", 4, 3,  "Amp"],
          ["S5.04", "BsmBI", 3, 2,  "Amp"],
          ["T1.01", "NmeAIII", 4, 2,  "Kan"],
          ["T1.02", "NmeAIII", 4, 3,  "Amp"],
          ["T1.03", "NmeAIII", 4, 3,  "Amp"],
          ["T2.01", "BsmBI", 3, 2,  "Amp"],
          ["T2.02", "BsmBI", 3, 2,  "Amp"],
          ["T2.03", "BsmBI", 3, 2,  "Amp"],
          ["T3.01", "BsaI", 2, 1,  "Kan"],
          ["T3.02", "NmeAIII", 4, 3,  "Amp"],
          ["T3.03", "NmeAIII", 4, 6,  "Amp"],
          ["T3.04", "NmeAIII", 4, 3,  "Amp"],
          ["T4.01", "NmeAIII", 4, 3,  "Amp"],
          ["T4.02", "NmeAIII", 4, 3,  "Amp"],
          ["T4.03", "NmeAIII", 4, 3,  "Amp"],
          ["T5.01", "NmeAIII", 4, 3,  "Amp"],
          ["T5.02", "BsmBI", 3, 2,  "Amp"],
          ["T5.03", "BsmBI", 3, 2,  "Kan"],
          ["T5.04", "BsmBI", 3, 2,  "Amp"],
          ["T6.01", "AarI", 1, 3,  "Kan"],
          ["T6.02", "NmeAIII", 4, 2,  "Kan"],
          ["T6.03", "BsmBI", 3, 2,  "Kan"],
          ["T6.04", "NmeAIII", 4, 2,  "Kan"],
          ["U1.01", "BsmBI", 3, 2,  "Amp"],
          ["U1.02", "BsmBI", 3, 2,  "Amp"],
          ["U1.03", "BsmBI", 3, 2,  "Amp"],
          ["U2.01", "BsmBI", 3, 2,  "Kan"],
          ["U2.02", "BsmBI", 3, 2,  "Kan"],
          ["U2.03", "BsmBI", 3, 2,  "Amp"],
          ["U3.01", "AarI", 1, 3,  "Kan"],
          ["U3.02", "BsmBI", 3, 2,  "Amp"],
          ["U3.03", "BsmBI", 3, 2,  "Amp"],
          ["U4.01", "NmeAIII", 4, 2,  "Kan"],
          ["U4.02", "BsmBI", 3, 2,  "Amp"],
          ["U4.03", "BsmBI", 3, 2,  "Kan"],
          ["U5.01", "NmeAIII", 4, 2,  "Kan"],
          ["U5.02", "NmeAIII", 4, 3,  "Kan"],
          ["U5.03", "BsmBI", 3, 2,  "Amp"],
          ["U5.04", "BsmBI", 3, 2,  "Amp"],
          ["V1.01", "BsmBI", 3, 2,  "Amp"],
          ["V1.02", "BsmBI", 3, 2,  "Kan"],
          ["V1.03", "BsmBI", 3, 2,  "Amp"],
          ["V2.01", "BsmBI", 3, 2,  "Amp"],
          ["V2.02", "BsmBI", 3, 2,  "Amp"],
          ["V2.03", "NmeAIII", 4, 3,  "Amp"],
          ["V2.04", "BsmBI", 3, 2,  "Amp"],
          ["V3.01", "BsmBI", 3, 2,  "Amp"],
          ["V3.02", "BsmBI", 3, 2,  "Kan"],
          ["V3.03", "BsmBI", 3, 2,  "Kan"],
          ["V4.01", "NmeAIII", 4, 6,  "Amp"],
          ["V4.02", "BsmBI", 3, 2,  "Kan"],
          ["V4.03", "BsmBI", 3, 2,  "Amp"],
          ["V5.01", "BsmBI", 3, 2,  "Amp"],
          ["V5.02", "NmeAIII", 4, 2,  "Kan"],
          ["V5.03", "NmeAIII", 4, 3,  "Amp"],
          ["V5.04", "AarI", 1, 3,  "Kan"],
          ["W1.01", "NmeAIII", 4, 6,  "Amp"],
          ["W1.02", "BsmBI", 3, 2,  "Kan"],
          ["W1.03", "BsmBI", 3, 2,  "Kan"],
          ["W2.01", "BsmBI", 3, 2,  "Amp"],
          ["W2.02", "BsmBI", 3, 2,  "Amp"],
          ["W2.03", "NmeAIII", 4, 3,  "Amp"],
          ["W2.04", "NmeAIII", 4, 6,  "Amp"],
          ["W3.01", "NmeAIII", 4, 2,  "Kan"],
          ["W3.02", "BsmBI", 3, 2,  "Kan"],
          ["W3.03", "BsmBI", 3, 2,  "Amp"],
          ["W4.01", "NmeAIII", 4, 3,  "Amp"],
          ["W4.02", "NmeAIII", 4, 3,  "Amp"],
          ["W4.03", "NmeAIII", 4, 3,  "Kan"],
          ["W4.04", "NmeAIII", 4, 2,  "Kan"],
          ["W5.01", "NmeAIII", 4, 2,  "Kan"],
          ["W5.02", "BsmBI", 3, 2,  "Amp"],
          ["W5.03", "BsmBI", 3, 2,  "Amp"],
          ["W5.04", "BsmBI", 3, 2,  "Amp"],
          ["X1.01", "BsmBI", 3, 2,  "Kan"],
          ["X1.02", "BsmBI", 3, 2,  "Kan"],
          ["X1.03", "NmeAIII", 4, 3,  "Amp"],
          ["X1.04", "AarI", 1, 3,  "Kan"],
          ["X2.01", "BsmBI", 3, 2,  "Amp"],
          ["X2.02", "BsmBI", 3, 2,  "Amp"],
          ["X2.03", "NmeAIII", 4, 3,  "Amp"],
          ["X2.04", "NmeAIII", 4, 3,  "Amp"],
          ["X3.01", "BsmBI", 3, 2,  "Amp"],
          ["X3.02", "BsaI", 2, 1,  "Kan"],
          ["X3.03", "BsmBI", 3, 2,  "Amp"],
          ["X4.01", "BsmBI", 3, 2,  "Amp"],
          ["X4.02", "BsmBI", 3, 2,  "Amp"],
          ["X4.03", "BsmBI", 3, 2,  "Amp"],
          ["X5.01", "BsmBI", 3, 2,  "Kan"],
          ["X5.02", "BsmBI", 3, 2,  "Amp"],
          ["X5.03", "BsmBI", 3, 2,  "Amp"],
          ["X5.04", "AarI", 1, 3,  "Kan"],
          ["Y1.01", "BsmBI", 3, 2,  "Kan"],
          ["Y1.02", "BsmBI", 3, 2,  "Amp"],
          ["Y1.03", "NmeAIII", 4, 3,  "Amp"],
          ["Y2.01", "NmeAIII", 4, 3,  "Kan"],
          ["Y2.02", "NmeAIII", 4, 2,  "Kan"],
          ["Y2.03", "BsmBI", 3, 2,  "Amp"],
          ["Y2.04", "NmeAIII", 4, 3,  "Amp"],
          ["Y3.01", "BsmBI", 3, 2,  "Amp"],
          ["Y3.02", "NmeAIII", 4, 3,  "Amp"],
          ["Y3.03", "BsmBI", 3, 2,  "Amp"],
          ["Y4.01", "BsmBI", 3, 2,  "Kan"],
          ["Y4.02", "NmeAIII", 4, 3,  "Amp"],
          ["Y4.03", "BsmBI", 3, 2,  "Amp"],
          ["Y4.04", "BsmBI", 3, 2,  "Kan"],
          ["Y5.01", "BsmBI", 3, 2,  "Kan"],
          ["Y5.02", "BsmBI", 3, 2,  "Kan"],
          ["Y5.03", "BsmBI", 3, 2,  "Amp"],
          ["Y5.04", "BsmBI", 3, 2,  "Kan"],
          ["Z1.01", "BsmBI", 3, 2,  "Amp"],
          ["Z1.02", "BsmBI", 3, 2,  "Kan"],
          ["Z1.03", "NmeAIII", 4, 3,  "Amp"],
          ["Z1.04", "BsaI", 2, 2,  "Kan"],
          ["Z2.01", "BsmBI", 3, 2,  "Amp"],
          ["Z2.02", "NmeAIII", 4, 3,  "Amp"],
          ["Z2.03", "BsmBI", 3, 2,  "Amp"],
          ["Z3.01", "BsmBI", 3, 2,  "Kan"],
          ["Z3.02", "BsmBI", 3, 2,  "Amp"],
          ["Z3.03", "NmeAIII", 4, 3,  "Amp"],
          ["Z3.04", "BsmBI", 3, 2,  "Amp"],
          ["Z4.01", "BsmBI", 3, 2,  "Kan"],
          ["Z4.02", "BsmBI", 3, 2,  "Kan"],
          ["Z4.03", "NmeAIII", 4, 3,  "Amp"],
          ["Z5.01", "BsmBI", 3, 2,  "Kan"],
          ["Z5.02", "BsmBI", 3, 2,  "Amp"],
          ["Z5.03", "NmeAIII", 4, 2,  "Kan"],
          ["Z6.01", "NmeAIII", 4, 3,  "Amp"],
          ["Z6.02", "BsmBI", 3, 2,  "Amp"],
          ["Z6.03", "BsmBI", 3, 2,  "Amp"],
          ["Z6.04", "NmeAIII", 4, 2,  "Kan"]]
  return m_ls

def chunk_dict():
     import re
     c_ls = chunk_ls()
     m_dict = {}
     for c in c_ls:
          s = re.search("[A-Z]*",c[0])
          m = s.group(0)
          if m in m_dict:
               if c[0] in m_dict[m]:
                    m_dict[m][c[0]].append(c[1])
               else:
                    m_dict[m][c[0]] = [c[1]]
          else:
               m_dict[m] = {c[0]:[c[1]]}
     return m_dict
def chunk_ls():
  c_ls = [["A1", "SfiI"],
          ["A1", "SfiI"],
          ["A2", "SfiI"],
          ["A2", "SfiI"],
          ["A3", "SfiI"],
          ["A3", "SfiI"],
          ["A4", "SfiI"],
          ["A4", "SfiI"],
          ["A5", "BsoBI"],
          ["A5", "SfiI"],
          ["A6", "BaeI"],
          ["A6", "SfiI"],
          ["AA1", "BglI"],
          ["AA1", "BglI"],
          ["AA2", "BglI"],
          ["AA2", "BglI"],
          ["AA3", "BglI"],
          ["AA3", "BstEII"],
          ["AA4", "BstEII"],
          ["AA4", "SfiI"],
          ["AA5", "BsoBI"],
          ["AA5", "SfiI"],
          ["AA6", "BaeI"],
          ["AA6", "SfiI"],
          ["B1", "BsiEI"],
          ["B1", "SfiI"],
          ["B2", "BsiEI"],
          ["B2", "SfiI"],
          ["B3", "SfiI"],
          ["B3", "SfiI"],
          ["B4", "SfiI"],
          ["B4", "SfiI"],
          ["B5", "BcgI"],
          ["B5", "SfiI"],
          ["BB1", "Eco31I"],
          ["BB1", "SfiI"],
          ["BB2", "BglI"],
          ["BB2", "Eco31I"],
          ["BB3", "BglI"],
          ["BB3", "BglI"],
          ["BB4", "BglI"],
          ["BB4", "BglI"],
          ["BB5", "BglI"],
          ["BB5", "BsiEI"],
          ["C1", "DraIII"],
          ["C1", "SfiI"],
          ["C2", "BsoBI"],
          ["C2", "SfiI"],
          ["C3", "BsoBI"],
          ["C3", "SfiI"],
          ["C4", "Bsu36I"],
          ["C4", "SfiI"],
          ["C5", "BaeI"],
          ["C5", "SfiI"],
          ["CC1", "BsiEI"],
          ["CC1", "BstEII"],
          ["CC2", "BstEII"],
          ["CC2", "SfiI"],
          ["CC3", "BsoBI"],
          ["CC3", "SfiI"],
          ["CC4", "BsoBI"],
          ["CC4", "SfiI"],
          ["CC5", "RsrII"],
          ["CC5", "SfiI"],
          ["CC6", "Bsu36I"],
          ["CC6", "RsrII"],
          ["D1", "BsoBI"],
          ["D1", "SfiI"],
          ["D2", "BsoBI"],
          ["D2", "BstEII"],
          ["D3", "BstEII"],
          ["D3", "SfiI"],
          ["D4", "SfiI"],
          ["D4", "SfiI"],
          ["D5", "BaeI"],
          ["D5", "Bsu36I"],
          ["DD1", "Bsu36I"],
          ["DD1", "SfiI"],
          ["DD2", "SfiI"],
          ["DD2", "SfiI"],
          ["DD3", "SfiI"],
          ["DD3", "SfiI"],
          ["DD4", "DraIII"],
          ["DD4", "SfiI"],
          ["DD5", "BaeI"],
          ["DD5", "DraIII"],
          ["E1", "Bsu36I"],
          ["E1", "SfiI"],
          ["E2", "SfiI"],
          ["E2", "SfiI"],
          ["E3", "SfiI"],
          ["E3", "SfiI"],
          ["E4", "BsmBI"],
          ["E4", "SfiI"],
          ["E5", "BaeI"],
          ["E5", "SfiI"],
          ["EE1", "SfiI"],
          ["EE1", "SfiI"],
          ["EE2", "SfiI"],
          ["EE2", "SfiI"],
          ["EE3", "SfiI"],
          ["EE3", "SfiI"],
          ["EE4", "BsoBI"],
          ["EE4", "SfiI"],
          ["EE5", "BaeI"],
          ["EE5", "BsoBI"],
          ["EE5", "RsrII"],
          ["F1", "SfiI"],
          ["F1", "SfiI"],
          ["F2", "SfiI"],
          ["F2", "SfiI"],
          ["F3", "BsoBI"],
          ["F3", "SfiI"],
          ["F4", "BsoBI"],
          ["F4", "SfiI"],
          ["F5", "BanI"],
          ["F5", "SfiI"],
          ["FF1", "RsrII"],
          ["FF1", "SfiI"],
          ["FF2", "BsoBI"],
          ["FF2", "SfiI"],
          ["FF3", "BsoBI"],
          ["FF3", "SfiI"],
          ["FF4", "SfiI"],
          ["FF4", "SfiI"],
          ["FF5", "BstEII"],
          ["FF5", "SfiI"],
          ["G1", "BanI"],
          ["G1", "SfiI"],
          ["G2", "SfiI"],
          ["G2", "SfiI"],
          ["G3", "SfiI"],
          ["G3", "SfiI"],
          ["G4", "BsoBI"],
          ["G4", "SfiI"],
          ["G5", "BaeI"],
          ["G5", "BsoBI"],
          ["GG1", "BstEII"],
          ["GG1", "SfiI"],
          ["GG2", "SfiI"],
          ["GG2", "SfiI"],
          ["GG3", "BsoBI"],
          ["GG3", "SfiI"],
          ["GG4", "BsoBI"],
          ["GG4", "Eco31I"],
          ["GG5", "Eco31I"],
          ["GG5", "SfiI"],
          ["H1", "BspQI"],
          ["H1", "SfiI"],
          ["H2", "SfiI"],
          ["H2", "SfiI"],
          ["H3", "BsoBI"],
          ["H3", "SfiI"],
          ["H4", "BglI"],
          ["H4", "BsoBI"],
          ["H5", "BcgI"],
          ["H5", "BglI"],
          ["HH1", "BanI"],
          ["HH1", "SfiI"],
          ["HH2", "BanI"],
          ["HH2", "SfiI"],
          ["HH3", "BsoBI"],
          ["HH3", "SfiI"],
          ["HH4", "BsoBI"],
          ["HH4", "SfiI"],
          ["HH5", "BstEII"],
          ["HH5", "SfiI"],
          ["I1", "BglI"],
          ["I1", "EcoO109I"],
          ["I2", "BglI"],
          ["I2", "BstEII"],
          ["I3", "BstEII"],
          ["I3", "EcoO109I"],
          ["I4", "EcoO109I"],
          ["I4", "SfiI"],
          ["I5", "DraIII"],
          ["I5", "SfiI"],
          ["I6", "DraIII"],
          ["I6", "SfiI"],
          ["II1", "BstEII"],
          ["II1", "SfiI"],
          ["II2", "SfiI"],
          ["II2", "SfiI"],
          ["II3", "BstXI"],
          ["II3", "SfiI"],
          ["II4", "BsoBI"],
          ["II4", "BstXI"],
          ["II4", "BstXI"],
          ["II5", "BaeI"],
          ["II5", "BtgI"],
          ["J1", "SfiI"],
          ["J1", "SfiI"],
          ["J2", "BstEII"],
          ["J2", "SfiI"],
          ["J3", "BglI"],
          ["J3", "BstEII"],
          ["J4", "BglI"],
          ["J4", "RsrII"],
          ["J5", "BglI"],
          ["J5", "RsrII"],
          ["JJ1", "BglI"],
          ["JJ1", "BtgI"],
          ["JJ2", "BglI"],
          ["JJ2", "BsoBI"],
          ["JJ3", "BsoBI"],
          ["JJ3", "BstEII"],
          ["JJ4", "BstEII"],
          ["JJ4", "BstEII"],
          ["JJ5", "BstEII"],
          ["JJ5", "BstEII"],
          ["K1", "BglI"],
          ["K1", "BstXI"],
          ["K2", "BstXI"],
          ["K2", "SfiI"],
          ["K3", "SfiI"],
          ["K3", "SfiI"],
          ["K4", "BsoBI"],
          ["K4", "SfiI"],
          ["K5", "BaeI"],
          ["K5", "SfiI"],
          ["L1", "BsoBI"],
          ["L1", "SfiI"],
          ["L2", "BsoBI"],
          ["L2", "BstEII"],
          ["L3", "BstEII"],
          ["L3", "SfiI"],
          ["L4", "SfiI"],
          ["L4", "SfiI"],
          ["L5", "BcgI"],
          ["L5", "SfiI"],
          ["M1", "BanI"],
          ["M1", "SfiI"],
          ["M1", "SfiI"],
          ["M2", "SfiI"],
          ["M2", "SfiI"],
          ["M3", "SfiI"],
          ["M3", "SfiI"],
          ["M4", "BstEII"],
          ["M4", "SfiI"],
          ["M5", "BaeI"],
          ["M5", "SfiI"],
          ["N1", "SfiI"],
          ["N1", "SfiI"],
          ["N2", "SfiI"],
          ["N2", "SfiI"],
          ["N3", "BsoBI"],
          ["N3", "SfiI"],
          ["N4", "BglI"],
          ["N4", "BsoBI"],
          ["N5", "BcgI"],
          ["N5", "BglI"],
          ["O1", "PflMI"],
          ["O1", "SfiI"],
          ["O2", "SfiI"],
          ["O2", "SfiI"],
          ["O3", "BsoBI"],
          ["O3", "SfiI"],
          ["O4", "BglI"],
          ["O4", "BsoBI"],
          ["O5", "BglI"],
          ["O5", "DraIII"],
          ["O6", "BsaXI"],
          ["O6", "SfiI"],
          ["P1", "SfiI"],
          ["P1", "SfiI"],
          ["P2", "BsoBI"],
          ["P2", "SfiI"],
          ["P3", "BsoBI"],
          ["P3", "SfiI"],
          ["P4", "BstEII"],
          ["P4", "SfiI"],
          ["P5", "BcgI"],
          ["P5", "SfiI"],
          ["Q1", "SfiI"],
          ["Q1", "SfiI"],
          ["Q2", "SfiI"],
          ["Q2", "SfiI"],
          ["Q3", "BsoBI"],
          ["Q3", "SfiI"],
          ["Q4", "BsoBI"],
          ["Q4", "BstEII"],
          ["Q5", "BstEII"],
          ["Q5", "SfiI"],
          ["R1", "BsoBI"],
          ["R1", "SfiI"],
          ["R2", "BsoBI"],
          ["R2", "SfiI"],
          ["R3", "EcoO109I"],
          ["R3", "SfiI"],
          ["R4", "EcoO109I"],
          ["R4", "SfiI"],
          ["R5", "BaeI"],
          ["R5", "SfiI"],
          ["S1", "BanI"],
          ["S1", "SfiI"],
          ["S2", "SfiI"],
          ["S2", "SfiI"],
          ["S3", "BsoBI"],
          ["S3", "SfiI"],
          ["S4", "BglI"],
          ["S4", "BsoBI"],
          ["S5", "BcgI"],
          ["S5", "BsoBI"],
          ["T1", "BsoBI"],
          ["T1", "SfiI"],
          ["T2", "SfiI"],
          ["T2", "SfiI"],
          ["T3", "DraIII"],
          ["T3", "SfiI"],
          ["T4", "BglI"],
          ["T4", "DraIII"],
          ["T5", "BglI"],
          ["T5", "BstXI"],
          ["T6", "BstXI"],
          ["T6", "RsrII"],
          ["U1", "BsoBI"],
          ["U1", "RsrII"],
          ["U2", "BsoBI"],
          ["U2", "SfiI"],
          ["U3", "BstEII"],
          ["U3", "SfiI"],
          ["U4", "BstEII"],
          ["U4", "SfiI"],
          ["U5", "BaeI"],
          ["U5", "SfiI"],
          ["V1", "BstEII"],
          ["V1", "SfiI"],
          ["V2", "BanI"],
          ["V2", "SfiI"],
          ["V3", "BanI"],
          ["V3", "BsoBI"],
          ["V4", "BsoBI"],
          ["V4", "DraIII"],
          ["V5", "BaeI"],
          ["V5", "SfiI"],
          ["W1", "SfiI"],
          ["W1", "SfiI"],
          ["W2", "SfiI"],
          ["W2", "SfiI"],
          ["W3", "SfiI"],
          ["W3", "SfiI"],
          ["W4", "BsoBI"],
          ["W4", "SfiI"],
          ["W5", "BsoBI"],
          ["W5", "SfiI"],
          ["X1", "SfiI"],
          ["X1", "SfiI"],
          ["X2", "BanII"],
          ["X2", "SfiI"],
          ["X3", "BanII"],
          ["X3", "SfiI"],
          ["X4", "SfiI"],
          ["X4", "SfiI"],
          ["X5", "BaeI"],
          ["X5", "SfiI"],
          ["Y1", "Bsu36I"],
          ["Y1", "SfiI"],
          ["Y2", "BanI"],
          ["Y2", "SfiI"],
          ["Y3", "BanI"],
          ["Y3", "BanI"],
          ["Y3", "BglI"],
          ["Y4", "BglI"],
          ["Y5", "BaeI"],
          ["Y5", "BsoBI"],
          ["Y5", "SfiI"],
          ["Z1", "SfiI"],
          ["Z1", "SfiI"],
          ["Z2", "SfiI"],
          ["Z2", "SfiI"],
          ["Z3", "SfiI"],
          ["Z3", "SfiI"],
          ["Z4", "SfiI"],
          ["Z4", "SfiI"],
          ["Z5", "EcoO109I"],
          ["Z5", "SfiI"],
          ["Z6", "BaeI"],
          ["Z6", "EcoO109I"]]
  return c_ls
if __name__ =="__main__":
     chunk_dict()    